name: CI


on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/Checkout@v2
      
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GHUSER }}
        password: ${{ secrets.GHTOKEN }}
      
    - run:
        docker build -t ghcr.io/tiagodallecio/pucdb/dbpuc:latest -f Dockerfile.
        docker tag ghcr.io/tiagodallecio/pucdb/dbpuc:latest ghcr.io/tiagodallecio/pucdb/dbpuc:${{ github.sha }}
      
    - run: 
       docker push ghcr.io/tiagodallecio/pucdb/dbpuc:latest
       docker push ghcr.io/tiagodallecio/pucdb/dbpuc:${{ github.sha }}
