name: CI


on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/Checkout@v2
      
    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GHUSER }}
        password: ${{ secrets.GHTOKEN }}
      
    - run:
        docker build -t ghcr.io/tiagodallecio/pucdb/postgres:14.5 -f Dockerfile .
        docker tag ghcr.io/tiagodallecio/pucdb/postgres:14.5 ghcr.io/tiagodallecio/pucdb/postgres:${{ github.sha }}
        
    - run: 
       docker push ghcr.io/tiagodallecio/pucdb/postgres:14.5 
       docker push ghcr.io/tiagodallecio/pucdb/postgres:${{ github.sha }}
       
